before_script:
    - apt update && apt install rsync openssh-client -y
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts

deploy to production:
  stage: deploy
  only:
    - main
  tags:
    - ubnt24
  environment:
    name: production
  script:
    - rsync -zrpth --stats --delete-after --exclude=.git $(pwd)/ deploy@$DEPLOY_SERVER:/path/to/helm
    - ssh deploy@$DEPLOY_SERVER "cd /path/to/helm && helm upgrade --install satis . -n satis && kubectl create job --from=cronjob/satis-build satis-manual-$(date +%s) -n satis"
#  when: manual
