apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    server {
      listen 80;
      server_name {{ .Values.satis.serverName }};

      root /usr/share/nginx/html;
      index index.html;

      location / {
          try_files $uri $uri/ =404;
          autoindex off;
      }

      location ~* ^/packages\.json$ {
          add_header Cache-Control "no-store";
      }
    }