apiVersion: batch/v1
kind: CronJob
metadata:
  name: satis-build
  namespace: {{ .Values.namespace }}
spec:
  schedule: "{{ .Values.builder.schedule }}"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: satis
            image: {{ .Values.builder.image }}
            args: ["build", "/satis/satis.json", "/satis/output"]
            volumeMounts:
            - name: config
              mountPath: /satis/satis.json
              subPath: satis.json
            - name: output
              mountPath: /satis/output
          restartPolicy: Never
          volumes:
          - name: config
            configMap:
              name: satis-config
          - name: output
            persistentVolumeClaim:
              claimName: satis-output-pvc