{{- if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.tls.secretName }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.tls.secretName }}
  dnsNames:
  - {{ .Values.tls.dnsNames }}
  issuerRef:
    name: {{ .Values.tls.clusterIssuer }}
    kind: ClusterIssuer
  usages:
  - digital signature
  - key encipherment
{{- end }}
